//go:build linux

package wayland

// libwayland_xdg.go — xdg-shell role for C Vulkan surface.
//
// Vulkan on Wayland requires the wl_surface to have an xdg_toplevel role.
// Without a role, the compositor won't composite the surface, buffer release
// events never arrive, and vkQueuePresentKHR blocks forever.
//
// xdg-shell interface descriptors (xdg_wm_base_interface, etc.) are NOT in
// libwayland-client.so — they're generated by wayland-scanner and compiled
// into each application. Since we're zero-CGO, we construct minimal
// C-compatible wl_interface structs in Go memory.
//
// Uses goffi callbacks for xdg_surface.configure (ack_configure) and
// xdg_wm_base.ping (pong) events.

import (
	"fmt"
	"log/slog"
	"runtime"
	"sync"
	"unsafe"

	"github.com/go-webgpu/goffi/ffi"
)

// cWlMessage matches C struct wl_message on 64-bit Linux (24 bytes).
type cWlMessage struct {
	Name      uintptr // const char *name
	Signature uintptr // const char *signature
	Types     uintptr // const struct wl_interface **types
}

// cWlInterface matches C struct wl_interface on 64-bit Linux (40 bytes).
type cWlInterface struct {
	Name        uintptr // const char *name
	Version     int32   // int version
	MethodCount int32   // int method_count
	Methods     uintptr // const struct wl_message *methods
	EventCount  int32   // int event_count
	_           int32   // alignment padding
	Events      uintptr // const struct wl_message *events
}

// cstr returns a uintptr to the string's underlying data.
// The string MUST contain an embedded null terminator (\x00) at the end.
// String constants are in the program's read-only data segment — stable for program lifetime.
func cstr(s string) uintptr {
	return uintptr(unsafe.Pointer(unsafe.StringData(s)))
}

// xdg interface descriptors — constructed once, live for program lifetime.
// All types arrays are NULL (no type validation for our simplified use).
var xdg struct {
	once sync.Once

	// Interface descriptors
	wmBase   cWlInterface
	surface  cWlInterface
	toplevel cWlInterface

	// Decoration interface descriptors (optional, zxdg_decoration_manager_v1)
	decorManager  cWlInterface
	toplevelDecor cWlInterface

	// Method arrays (indexed by opcode)
	wmBaseMethods   [4]cWlMessage  // destroy, create_positioner, get_xdg_surface, pong
	surfaceMethods  [5]cWlMessage  // destroy, get_toplevel, get_popup, set_window_geometry, ack_configure
	toplevelMethods [14]cWlMessage // all 14 xdg_toplevel requests

	// Decoration method arrays
	decorManagerMethods  [2]cWlMessage // destroy, get_toplevel_decoration
	toplevelDecorMethods [3]cWlMessage // destroy, set_mode, unset_mode

	// Event arrays (indexed by event opcode)
	wmBaseEvents   [1]cWlMessage // ping
	surfaceEvents  [1]cWlMessage // configure
	toplevelEvents [4]cWlMessage // configure, close, configure_bounds (v4), wm_capabilities (v5)

	// Decoration event arrays
	toplevelDecorEvents [1]cWlMessage // configure

	// NULL types array (shared by all messages)
	nullTypes [8]uintptr
}

// initXdgInterfaces constructs the C-compatible xdg-shell interface descriptors.
// Called once during the first OpenLibwayland call that requests xdg role.
func initXdgInterfaces() {
	xdg.once.Do(func() {
		nt := uintptr(unsafe.Pointer(&xdg.nullTypes[0]))

		// === xdg_wm_base methods ===
		xdg.wmBaseMethods[0] = cWlMessage{cstr("destroy\x00"), cstr("\x00"), nt}
		xdg.wmBaseMethods[1] = cWlMessage{cstr("create_positioner\x00"), cstr("n\x00"), nt}
		xdg.wmBaseMethods[2] = cWlMessage{cstr("get_xdg_surface\x00"), cstr("no\x00"), nt}
		xdg.wmBaseMethods[3] = cWlMessage{cstr("pong\x00"), cstr("u\x00"), nt}

		// xdg_wm_base events
		xdg.wmBaseEvents[0] = cWlMessage{cstr("ping\x00"), cstr("u\x00"), nt}

		// xdg_wm_base interface
		xdg.wmBase = cWlInterface{
			Name:        cstr("xdg_wm_base\x00"),
			Version:     6,
			MethodCount: 4,
			Methods:     uintptr(unsafe.Pointer(&xdg.wmBaseMethods[0])),
			EventCount:  1,
			Events:      uintptr(unsafe.Pointer(&xdg.wmBaseEvents[0])),
		}

		// === xdg_surface methods ===
		xdg.surfaceMethods[0] = cWlMessage{cstr("destroy\x00"), cstr("\x00"), nt}
		xdg.surfaceMethods[1] = cWlMessage{cstr("get_toplevel\x00"), cstr("n\x00"), nt}
		xdg.surfaceMethods[2] = cWlMessage{cstr("get_popup\x00"), cstr("n?oo\x00"), nt}
		xdg.surfaceMethods[3] = cWlMessage{cstr("set_window_geometry\x00"), cstr("iiii\x00"), nt}
		xdg.surfaceMethods[4] = cWlMessage{cstr("ack_configure\x00"), cstr("u\x00"), nt}

		// xdg_surface events
		xdg.surfaceEvents[0] = cWlMessage{cstr("configure\x00"), cstr("u\x00"), nt}

		// xdg_surface interface
		xdg.surface = cWlInterface{
			Name:        cstr("xdg_surface\x00"),
			Version:     6,
			MethodCount: 5,
			Methods:     uintptr(unsafe.Pointer(&xdg.surfaceMethods[0])),
			EventCount:  1,
			Events:      uintptr(unsafe.Pointer(&xdg.surfaceEvents[0])),
		}

		// === xdg_toplevel methods (all 14 per xdg-shell spec) ===
		xdg.toplevelMethods[0] = cWlMessage{cstr("destroy\x00"), cstr("\x00"), nt}
		xdg.toplevelMethods[1] = cWlMessage{cstr("set_parent\x00"), cstr("?o\x00"), nt}
		xdg.toplevelMethods[2] = cWlMessage{cstr("set_title\x00"), cstr("s\x00"), nt}
		xdg.toplevelMethods[3] = cWlMessage{cstr("set_app_id\x00"), cstr("s\x00"), nt}
		xdg.toplevelMethods[4] = cWlMessage{cstr("show_window_menu\x00"), cstr("ouii\x00"), nt}
		xdg.toplevelMethods[5] = cWlMessage{cstr("move\x00"), cstr("ou\x00"), nt}
		xdg.toplevelMethods[6] = cWlMessage{cstr("resize\x00"), cstr("ouu\x00"), nt}
		xdg.toplevelMethods[7] = cWlMessage{cstr("set_max_size\x00"), cstr("ii\x00"), nt}
		xdg.toplevelMethods[8] = cWlMessage{cstr("set_min_size\x00"), cstr("ii\x00"), nt}
		xdg.toplevelMethods[9] = cWlMessage{cstr("set_maximized\x00"), cstr("\x00"), nt}
		xdg.toplevelMethods[10] = cWlMessage{cstr("unset_maximized\x00"), cstr("\x00"), nt}
		xdg.toplevelMethods[11] = cWlMessage{cstr("set_fullscreen\x00"), cstr("?o\x00"), nt}
		xdg.toplevelMethods[12] = cWlMessage{cstr("unset_fullscreen\x00"), cstr("\x00"), nt}
		xdg.toplevelMethods[13] = cWlMessage{cstr("set_minimized\x00"), cstr("\x00"), nt}

		// xdg_toplevel events (all 4 events per xdg-shell v6 protocol spec)
		xdg.toplevelEvents[0] = cWlMessage{cstr("configure\x00"), cstr("iia\x00"), nt}
		xdg.toplevelEvents[1] = cWlMessage{cstr("close\x00"), cstr("\x00"), nt}
		xdg.toplevelEvents[2] = cWlMessage{cstr("configure_bounds\x00"), cstr("4ii\x00"), nt} // since v4
		xdg.toplevelEvents[3] = cWlMessage{cstr("wm_capabilities\x00"), cstr("5a\x00"), nt}   // since v5

		// xdg_toplevel interface
		xdg.toplevel = cWlInterface{
			Name:        cstr("xdg_toplevel\x00"),
			Version:     6,
			MethodCount: 14,
			Methods:     uintptr(unsafe.Pointer(&xdg.toplevelMethods[0])),
			EventCount:  4,
			Events:      uintptr(unsafe.Pointer(&xdg.toplevelEvents[0])),
		}

		// === zxdg_decoration_manager_v1 methods ===
		xdg.decorManagerMethods[0] = cWlMessage{cstr("destroy\x00"), cstr("\x00"), nt}
		xdg.decorManagerMethods[1] = cWlMessage{cstr("get_toplevel_decoration\x00"), cstr("no\x00"), nt}

		// zxdg_decoration_manager_v1 interface
		xdg.decorManager = cWlInterface{
			Name:        cstr("zxdg_decoration_manager_v1\x00"),
			Version:     1,
			MethodCount: 2,
			Methods:     uintptr(unsafe.Pointer(&xdg.decorManagerMethods[0])),
			EventCount:  0,
			Events:      0,
		}

		// === zxdg_toplevel_decoration_v1 methods ===
		xdg.toplevelDecorMethods[0] = cWlMessage{cstr("destroy\x00"), cstr("\x00"), nt}
		xdg.toplevelDecorMethods[1] = cWlMessage{cstr("set_mode\x00"), cstr("u\x00"), nt}
		xdg.toplevelDecorMethods[2] = cWlMessage{cstr("unset_mode\x00"), cstr("\x00"), nt}

		// zxdg_toplevel_decoration_v1 events
		xdg.toplevelDecorEvents[0] = cWlMessage{cstr("configure\x00"), cstr("u\x00"), nt}

		// zxdg_toplevel_decoration_v1 interface
		xdg.toplevelDecor = cWlInterface{
			Name:        cstr("zxdg_toplevel_decoration_v1\x00"),
			Version:     1,
			MethodCount: 3,
			Methods:     uintptr(unsafe.Pointer(&xdg.toplevelDecorMethods[0])),
			EventCount:  1,
			Events:      uintptr(unsafe.Pointer(&xdg.toplevelDecorEvents[0])),
		}
	})
}

// xdgHandlesMu guards the maps below, which route xdg callbacks to the
// correct LibwaylandHandle when multiple windows are open simultaneously.
var (
	xdgHandlesMu       sync.Mutex
	xdgSurfaceHndls    = make(map[uintptr]*LibwaylandHandle) // wl_surface proxy → handle
	xdgWmBaseHndls     = make(map[uintptr]*LibwaylandHandle) // xdg_wm_base proxy → handle
	toplevelDecorHndls = make(map[uintptr]*LibwaylandHandle) // zxdg_toplevel_decoration_v1* proxy → handle
)

// xdgSurfaceConfigureCb handles xdg_surface.configure(data, xdg_surface, serial).
// Called from C via goffi trampoline during wl_display_dispatch.
// Acks the configure event so the compositor maps the surface.
func xdgSurfaceConfigureCb(data, xdgSurface, serial uintptr) {
	xdgHandlesMu.Lock()
	h := xdgSurfaceHndls[xdgSurface]
	xdgHandlesMu.Unlock()
	if h == nil {
		return
	}
	slog.Debug("xdg_surface.configure", "serial", uint32(serial), "configuredW", h.configuredW, "configuredH", h.configuredH)

	// ack_configure = xdg_surface opcode 4, arg: serial (uint32)
	h.marshalVoid(h.xdgSurface, 4, serial)
	slog.Debug("ack_configure sent", "serial", uint32(serial))

	// Mark initial configure received — unblocks WaitForConfigure (ADR-041).
	h.initialConfigureReceived = true

	// Resize CSD subsurfaces AFTER ack_configure, BEFORE parent commit.
	// Subsurfaces in sync mode have their state applied atomically with the parent commit.
	// This is the GLFW pattern: ack_configure -> resizeWindow -> commit.
	if h.csdPendingResize {
		h.csdPendingResize = false
		// Clear csdPendingRepaint AFTER ResizeCSD: state-change-triggered resizes
		// (same dimensions, different maximize/fullscreen state) set csdPendingRepaint=true
		// in inputToplevelConfigureCb so ResizeCSD bypasses its early-return guard.
		// Clearing before the call would drop that signal and skip the hide/show logic
		// (issue #300).
		h.ResizeCSD(h.csdPendingResizeW, h.csdPendingResizeH)
		h.csdPendingRepaint = false
	}

	// Window geometry per state (winit/libdecor enterprise pattern):
	//   Normal:     (0, 0, contentW, contentH) — title bar outside geometry (CSD standard)
	//   Maximize:   (0, -tbH, contentW, contentH+tbH) — title bar inside geometry via negative offset
	//   Fullscreen: (0, 0, configW, configH) — no decorations, full area
	if h.csdActive && h.csdContentW > 0 {
		tbH := h.csdPainter.TitleBarHeight()
		geoX := int32(0)
		geoY := int32(0)
		geoW := h.csdContentW
		geoH := h.csdContentH
		if h.csdState.Fullscreen {
			geoW = h.configuredW
			geoH = h.configuredH
		} else if h.csdState.Maximized {
			geoY = -int32(tbH)
			geoH = h.csdContentH + tbH
		}
		slog.Debug("set_window_geometry CSD", "x", geoX, "y", geoY, "w", geoW, "h", geoH)
		h.marshalVoid(h.xdgSurface, 3, uintptr(uint32(geoX)), uintptr(uint32(geoY)),
			uintptr(uint32(geoW)), uintptr(uint32(geoH)))
	} else if h.configuredW > 0 && h.configuredH > 0 {
		slog.Debug("set_window_geometry non-CSD", "w", h.configuredW, "h", h.configuredH)
		h.marshalVoid(h.xdgSurface, 3, 0, 0,
			uintptr(uint32(h.configuredW)), uintptr(uint32(h.configuredH)))
	}

	// Damage entire buffer before commit so compositor knows what changed (#272).
	// wl_surface.damage_buffer = opcode 9 (v4+), signature "iiii".
	if h.configuredW > 0 && h.configuredH > 0 {
		h.marshalVoid(h.surface, 9, 0, 0,
			uintptr(uint32(h.configuredW)), uintptr(uint32(h.configuredH)))
	}

	// Commit the main surface — atomic: ack + geometry + damage + subsurface changes.
	h.marshalVoid(h.surface, 6)
	slog.Debug("parent surface committed")
}

// xdgWmBasePingCb handles xdg_wm_base.ping(data, xdg_wm_base, serial).
// Responds with pong to keep the connection alive.
func xdgWmBasePingCb(data, wmBase, serial uintptr) {
	xdgHandlesMu.Lock()
	h := xdgWmBaseHndls[wmBase]
	xdgHandlesMu.Unlock()
	if h == nil {
		return
	}
	// pong = xdg_wm_base opcode 3, arg: serial (uint32)
	h.marshalVoid(h.xdgWmBase, 3, serial)
}

// Listener arrays (package-level, must outlive the proxy).
// Each is an array of function pointers, one per event.
var (
	xdgSurfaceListener    [1]uintptr // [0] = configure callback
	xdgWmBaseListener     [1]uintptr // [0] = ping callback
	toplevelDecorListener [1]uintptr // [0] = configure callback
	listenersOnce         sync.Once
)

func initXdgListeners() {
	listenersOnce.Do(func() {
		xdgSurfaceListener[0] = ffi.NewCallback(xdgSurfaceConfigureCb)
		xdgWmBaseListener[0] = ffi.NewCallback(xdgWmBasePingCb)
		toplevelDecorListener[0] = ffi.NewCallback(decorConfigureCb)
	})
}

// decorConfigureCb handles zxdg_toplevel_decoration_v1.configure(data, decor, mode).
// Called before xdg_surface.configure when the compositor sets the decoration mode.
// mode: 1 = CLIENT_SIDE (app must draw CSD), 2 = SERVER_SIDE (compositor draws SSD).
// KDE Plasma may honor the SERVER_SIDE request or override to CLIENT_SIDE; without
// this listener the app never knows the compositor rejected SSD.
func decorConfigureCb(data, decoration, mode uintptr) {
	xdgHandlesMu.Lock()
	h := toplevelDecorHndls[decoration]
	xdgHandlesMu.Unlock()
	if h != nil {
		h.decorMode = uint32(mode)
		slog.Debug("zxdg_toplevel_decoration.configure", "mode", mode)
	}
}

// setupXdgRole gives the C wl_surface an xdg_toplevel role.
// This is required for Vulkan presentation — without a role, the compositor
// won't composite the surface, and vkQueuePresentKHR blocks forever.
//
// Protocol flow:
//  1. Bind xdg_wm_base (using global name from pure Go registry)
//  2. Create xdg_surface from wl_surface
//  3. Create xdg_toplevel from xdg_surface
//  4. Register configure listener
//  5. Initial commit (empty, per xdg-shell spec)
//  6. Roundtrip (processes configure event, callback acks it)
//  7. Second commit (surface is now configured)
func (h *LibwaylandHandle) setupXdgRole(xdgName, xdgVersion, decorName, decorVersion uint32) error {
	initXdgInterfaces()
	initXdgListeners()

	// Bind xdg_wm_base via registry.bind (same pattern as compositor binding)
	version := xdgVersion
	if version > 6 {
		version = 6
	}
	wmBase, err := h.registryBind(xdgName, unsafe.Pointer(&xdg.wmBase), version)
	if err != nil {
		return fmt.Errorf("wayland: failed to bind xdg_wm_base: %w", err)
	}
	h.xdgWmBase = wmBase

	// Register ping listener on xdg_wm_base
	if err := h.addListener(wmBase, uintptr(unsafe.Pointer(&xdgWmBaseListener[0]))); err != nil {
		return fmt.Errorf("wayland: failed to add xdg_wm_base listener: %w", err)
	}

	// Create xdg_surface — opcode 2, signature "no" (new_id, object)
	xdgSurf, err := h.marshalConstructorObj(wmBase, 2, unsafe.Pointer(&xdg.surface), h.surface)
	if err != nil {
		return fmt.Errorf("wayland: failed to create xdg_surface: %w", err)
	}
	h.xdgSurface = xdgSurf

	// Register configure listener on xdg_surface
	if err := h.addListener(xdgSurf, uintptr(unsafe.Pointer(&xdgSurfaceListener[0]))); err != nil {
		return fmt.Errorf("wayland: failed to add xdg_surface listener: %w", err)
	}

	// Create xdg_toplevel — opcode 1, signature "n" (new_id)
	toplevel, err := h.marshalConstructor(xdgSurf, 1, unsafe.Pointer(&xdg.toplevel))
	if err != nil {
		return fmt.Errorf("wayland: failed to create xdg_toplevel: %w", err)
	}
	h.xdgToplevel = toplevel

	// Request server-side decorations if compositor supports them.
	// Must be done BEFORE the initial commit per xdg-decoration protocol.
	if decorName != 0 {
		h.setupDecorations(decorName, decorVersion)
	}

	// Initial empty commit (required by xdg-shell spec before configure)
	h.marshalVoid(h.surface, 6) // wl_surface::commit = opcode 6

	// Flush all buffered requests
	if err := h.flush(); err != nil {
		return fmt.Errorf("wayland: flush before roundtrip failed: %w", err)
	}

	// Register this handle in the per-proxy maps so callbacks route to the right
	// LibwaylandHandle when multiple windows (connections) are open.
	xdgHandlesMu.Lock()
	xdgSurfaceHndls[h.xdgSurface] = h
	xdgWmBaseHndls[h.xdgWmBase] = h
	if h.toplevelDecor != 0 {
		toplevelDecorHndls[h.toplevelDecor] = h
	}
	xdgHandlesMu.Unlock()

	// Block until compositor sends xdg_surface.configure (ADR-041 configure gate).
	// A single roundtrip is NOT guaranteed to deliver configure — the compositor
	// may batch events or introduce delay. WaitForConfigure loops roundtrips
	// until the configure callback fires and sets initialConfigureReceived.
	slog.Debug("wayland: waiting for initial xdg_surface.configure")
	if err := h.WaitForConfigure(); err != nil {
		return fmt.Errorf("wayland: wait for xdg configure failed: %w", err)
	}
	slog.Debug("wayland: initial configure complete")

	// Second commit after configure ack (surface is now fully configured)
	h.marshalVoid(h.surface, 6) // wl_surface::commit

	// Final flush
	if err := h.flush(); err != nil {
		return fmt.Errorf("wayland: flush after xdg setup failed: %w", err)
	}

	return nil
}

// marshalConstructorObj calls wl_proxy_marshal_array_constructor for requests
// with signature "no" (new_id + object). Used for xdg_wm_base.get_xdg_surface.
func (h *LibwaylandHandle) marshalConstructorObj(proxy uintptr, opcode uint32, iface unsafe.Pointer, obj uintptr) (uintptr, error) {
	var argBuf [2]uintptr
	argBuf[0] = 0   // new_id placeholder
	argBuf[1] = obj // object argument (wl_surface proxy)
	argPtr := uintptr(unsafe.Pointer(&argBuf[0]))
	ifaceAddr := uintptr(iface)

	var result uintptr
	args := [4]unsafe.Pointer{
		unsafe.Pointer(&proxy),
		unsafe.Pointer(&opcode),
		unsafe.Pointer(&argPtr),
		unsafe.Pointer(&ifaceAddr),
	}
	_, _ = ffi.CallFunction(&h.cifMarshal, h.fnProxyMarshal, unsafe.Pointer(&result), args[:])
	if result == 0 {
		return 0, fmt.Errorf("wl_proxy_marshal_array_constructor returned NULL (opcode %d)", opcode)
	}
	return result, nil
}

// marshalVoid sends a request without creating a new proxy.
// Uses wl_proxy_marshal_array_constructor with NULL interface.
// This works for all void requests (set_title, commit, attach, move, resize).
func (h *LibwaylandHandle) marshalVoid(proxy uintptr, opcode uint32, args ...uintptr) {
	var argBuf [8]uintptr
	copy(argBuf[:], args)
	argPtr := uintptr(unsafe.Pointer(&argBuf[0]))
	var nullIface uintptr
	var dummyResult uintptr

	ffiArgs := [4]unsafe.Pointer{
		unsafe.Pointer(&proxy),
		unsafe.Pointer(&opcode),
		unsafe.Pointer(&argPtr),
		unsafe.Pointer(&nullIface),
	}
	_, _ = ffi.CallFunction(&h.cifMarshal, h.fnProxyMarshal, unsafe.Pointer(&dummyResult), ffiArgs[:])
}

// addListener calls wl_proxy_add_listener(proxy, listener, NULL).
func (h *LibwaylandHandle) addListener(proxy uintptr, listener uintptr) error {
	return h.addListenerWithData(proxy, listener, 0)
}

// addListenerWithData calls wl_proxy_add_listener with an explicit user-data pointer.
// Pass uintptr(unsafe.Pointer(h)) to have each callback receive h as its first argument,
// which avoids the need for a per-type global handle variable.
func (h *LibwaylandHandle) addListenerWithData(proxy, listener, data uintptr) error {
	var result int32
	args := [3]unsafe.Pointer{
		unsafe.Pointer(&proxy),
		unsafe.Pointer(&listener),
		unsafe.Pointer(&data),
	}
	_, _ = ffi.CallFunction(&h.cifAddListener, h.fnAddListener, unsafe.Pointer(&result), args[:])
	if result < 0 {
		return fmt.Errorf("wl_proxy_add_listener failed: %d", result)
	}
	return nil
}

// roundtrip calls wl_display_roundtrip_queue(display, appQueue) if the app queue
// is active, otherwise falls back to wl_display_roundtrip(display).
// Using the queue-specific variant ensures roundtrip only dispatches our objects'
// events, never Mesa Vulkan WSI's internal callbacks (ADR-041 Phase 4).
func (h *LibwaylandHandle) roundtrip() error {
	var result int32
	if h.appQueue != 0 {
		args := [2]unsafe.Pointer{unsafe.Pointer(&h.display), unsafe.Pointer(&h.appQueue)}
		_, _ = ffi.CallFunction(&h.cifRoundtripQueue, h.fnRoundtripQueue, unsafe.Pointer(&result), args[:])
		if result < 0 {
			return fmt.Errorf("wl_display_roundtrip_queue failed: %d", result)
		}
	} else {
		args := [1]unsafe.Pointer{unsafe.Pointer(&h.display)}
		_, _ = ffi.CallFunction(&h.cifRoundtrip, h.fnRoundtrip, unsafe.Pointer(&result), args[:])
		if result < 0 {
			return fmt.Errorf("wl_display_roundtrip failed: %d", result)
		}
	}
	return nil
}

// setupDecorations binds zxdg_decoration_manager_v1 and requests server-side
// decorations for the C xdg_toplevel. Registers a listener so that
// decorConfigureCb records the compositor's actual mode (SERVER_SIDE or
// CLIENT_SIDE) into h.decorMode — callers check DecorationMode() after
// WaitForConfigure to decide whether CSD is needed.
func (h *LibwaylandHandle) setupDecorations(decorName, decorVersion uint32) {
	version := decorVersion
	if version > 1 {
		version = 1
	}

	decorMgr, err := h.registryBind(decorName, unsafe.Pointer(&xdg.decorManager), version)
	if err != nil {
		return
	}
	h.decorManager = decorMgr

	// get_toplevel_decoration: opcode 1, signature "no" (new_id + object)
	decoration, err := h.marshalConstructorObj(decorMgr, 1, unsafe.Pointer(&xdg.toplevelDecor), h.xdgToplevel)
	if err != nil {
		return
	}
	h.toplevelDecor = decoration

	// Register configure listener BEFORE set_mode so we don't miss the event.
	// The compositor sends configure before xdg_surface.configure, so it arrives
	// within the same WaitForConfigure roundtrip batch.
	initXdgListeners()
	_ = h.addListener(decoration, uintptr(unsafe.Pointer(&toplevelDecorListener[0])))

	// set_mode(SERVER_SIDE=2): opcode 1, signature "u"
	h.marshalVoid(decoration, 1, 2)
}

// DecorationMode returns the decoration mode agreed by the compositor.
// 0 = protocol not available or configure not yet received (treat as CLIENT_SIDE).
// 1 = CLIENT_SIDE (app must draw CSD).
// 2 = SERVER_SIDE (compositor draws decorations; CSD not needed).
func (h *LibwaylandHandle) DecorationMode() uint32 {
	return h.decorMode
}

// SetTitle sets the window title on the C xdg_toplevel.
// Uses xdg_toplevel.set_title (opcode 2, signature "s").
func (h *LibwaylandHandle) SetTitle(title string) {
	if h.xdgToplevel == 0 || title == "" {
		return
	}
	buf := make([]byte, len(title)+1)
	copy(buf, title)
	h.marshalVoid(h.xdgToplevel, 2, uintptr(unsafe.Pointer(&buf[0])))
	runtime.KeepAlive(buf)
}

// SetAppID sets the application ID on the C xdg_toplevel.
// Uses xdg_toplevel.set_app_id (opcode 3, signature "s").
func (h *LibwaylandHandle) SetAppID(appID string) {
	if h.xdgToplevel == 0 || appID == "" {
		return
	}
	buf := make([]byte, len(appID)+1)
	copy(buf, appID)
	h.marshalVoid(h.xdgToplevel, 3, uintptr(unsafe.Pointer(&buf[0])))
	runtime.KeepAlive(buf)
}

// SetMinSize sets the minimum window size on the C xdg_toplevel.
// Uses xdg_toplevel.set_min_size (opcode 8, signature "ii").
func (h *LibwaylandHandle) SetMinSize(width, height int32) {
	if h.xdgToplevel == 0 {
		return
	}
	h.marshalVoid(h.xdgToplevel, 8, uintptr(uint32(width)), uintptr(uint32(height)))
}

// SetMaxSize sets the maximum window size on the C xdg_toplevel.
// Uses xdg_toplevel.set_max_size (opcode 7, signature "ii").
func (h *LibwaylandHandle) SetMaxSize(width, height int32) {
	if h.xdgToplevel == 0 {
		return
	}
	h.marshalVoid(h.xdgToplevel, 7, uintptr(uint32(width)), uintptr(uint32(height)))
}

// SetFullscreen requests fullscreen mode on the C xdg_toplevel.
// Uses xdg_toplevel.set_fullscreen (opcode 11, signature "?o").
func (h *LibwaylandHandle) SetFullscreen() {
	if h.xdgToplevel == 0 {
		return
	}
	h.marshalVoid(h.xdgToplevel, 11, 0) // NULL output = default
}

// Toplevel returns the xdg_toplevel proxy pointer.
// Used by CSD for move/resize operations.
func (h *LibwaylandHandle) Toplevel() uintptr {
	return h.xdgToplevel
}

// MarshalVoidOnToplevel sends a void request to the xdg_toplevel.
// Used for minimize, maximize, unset_maximized, fullscreen, etc.
func (h *LibwaylandHandle) MarshalVoidOnToplevel(opcode uint32, args ...uintptr) {
	if h.xdgToplevel == 0 {
		return
	}
	h.marshalVoid(h.xdgToplevel, opcode, args...)
	_ = h.flush()
}

// InputSeat returns the main input seat proxy pointer.
// Used by platform for serial-based operations.
func (h *LibwaylandHandle) InputSeat() uintptr {
	return h.inputSeat
}

// Flush sends all buffered requests to the compositor.
func (h *LibwaylandHandle) Flush() error {
	return h.flush()
}

// UnregisterXdgProxies removes this handle from the per-proxy xdg callback maps.
// Must be called before Close() to prevent stale map entries.
func (h *LibwaylandHandle) UnregisterXdgProxies() {
	xdgHandlesMu.Lock()
	delete(xdgSurfaceHndls, h.xdgSurface)
	delete(xdgWmBaseHndls, h.xdgWmBase)
	delete(toplevelDecorHndls, h.toplevelDecor)
	xdgHandlesMu.Unlock()
}

// Roundtrip performs a blocking roundtrip to the compositor.
func (h *LibwaylandHandle) Roundtrip() error {
	return h.roundtrip()
}
